tf.keras.backend.clear_session() # add it before calling the functional API model
# Resets all state generated by Keras.
# Keras manages a global state, which it uses to implement the Functional model-building API and to uniquify autogenerated layer names.
# If you are creating many models in a loop, this global state will consume an increasing amount of memory over time, and you may want to clear it. 
# Calling clear_session() releases the global state: this helps avoid clutter from old models and layers, especially when memory is limited.
